services:
  knowledge-search:
    container_name: knowledge-search-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/knowledge-search
    ports:
      - "8888:8888"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"