name: knowledge-search-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - python-dotenv
  - langchain-huggingface
  - langchain-text-splitters
  - langchain-community
  - qdrant-client
  - transformers
  - pip
  - pip:
    - pypdf

# Use conda depdencies above where possible. This is because:
# - Dependency resolution handled more robustly especially for non-python dependencies. Pip focuses on Python packages
# - Conda packages built specifically for certain environments
# - Conda installs pre-compiled binaries, which can be faster